# Generated by Django 4.2.1 on 2023-06-20 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_orders', models.IntegerField(db_index=True, null=True, verbose_name='Замовлення')),
                ('count_products', models.IntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('currency', models.CharField(max_length=100)),
                ('status', models.CharField(default='В процесі', max_length=100, null=True, verbose_name='Статус замовлення')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Продукт')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавець')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('post_index', models.IntegerField(verbose_name='Поштовий індекс')),
                ('count_products', models.IntegerField(default=1, verbose_name='Загальна кількість продуктів')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Замовник')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-id'],
            },
        ),
    ]
