# Generated by Django 4.2.1 on 2023-06-15 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('post_index', models.IntegerField(verbose_name='Поштовий індекс')),
                ('count_products', models.IntegerField(default=1, verbose_name='Кількість продуктів')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('price', models.FloatField(verbose_name='Ціна замовлення')),
                ('currency', models.CharField(max_length=100, verbose_name='Валюта')),
                ('status', models.CharField(default='В процесі', max_length=100, verbose_name='Статус замовлення')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Замовник')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Продукт')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Продавець')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-id'],
            },
        ),
    ]
