# Generated by Django 4.2.1 on 2023-06-18 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersproducts',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='number_photo',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='time_update',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='ordersproducts',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='count_products',
            field=models.IntegerField(default=1, verbose_name='Загальна кількість продуктів'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='В процесі', max_length=100, verbose_name='Статус замовлення'),
        ),
        migrations.AddField(
            model_name='ordersproducts',
            name='count_products',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordersproducts',
            name='number_orders',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Замовлення'),
        ),
        migrations.AddField(
            model_name='ordersproducts',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Продукт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersproducts',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавець'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersproducts',
            name='status',
            field=models.CharField(default='В процесі', max_length=100, verbose_name='Статус замовлення'),
        ),
        migrations.AlterField(
            model_name='ordersproducts',
            name='currency',
            field=models.CharField(max_length=100),
        ),
    ]
