# Generated by Django 4.2.1 on 2023-06-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_read',
        ),
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(default=1, max_length=100, verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=1, verbose_name='Ціна замовлення'),
            preserve_default=False,
        ),
    ]
