# Generated by Django 4.2.1 on 2023-06-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersproducts',
            old_name='number_products',
            new_name='number_orders',
        ),
    ]
