# Generated by Django 4.2.1 on 2023-05-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_currency_delete_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Валюти')),
            ],
            options={
                'verbose_name': 'Валюту',
                'verbose_name_plural': 'Валюти',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.currency', verbose_name='Валюти'),
            preserve_default=False,
        ),
    ]
