# Generated by Django 4.2.1 on 2023-06-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_price_ordersproducts_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AlterField(
            model_name='ordersproducts',
            name='status',
            field=models.CharField(default='В процесі', max_length=100, null=True, verbose_name='Статус замовлення'),
        ),
    ]
