# Generated by Django 4.2.1 on 2023-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_cat_orders_category_remove_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number_photo',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Фотографії'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='number_photo',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
