# Generated by Django 4.2.1 on 2023-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_number_products_ordersproducts_number_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersproducts',
            name='count',
        ),
        migrations.AddField(
            model_name='orders',
            name='count_products',
            field=models.IntegerField(default=1, verbose_name='Кількість продуктів'),
        ),
    ]
