# Generated by Django 4.2.1 on 2023-06-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_status_alter_ordersproducts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
    ]
