# Generated by Django 4.2.1 on 2023-06-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='start',
            new_name='stars',
        ),
    ]
